version: "3"

services:
  mysqlbackup:
    image: "mysqlbackup"
    stdin_open: true
    tty: true
    build: 
      context: ./mysql-backup
    container_name: mysql-backup
    environment:
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-}
      MYSQL_HOST: ${MYSQL_HOST:-127.0.0.1}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      CRON_TIME: ${MYSQLBACKUP_CRON_TIME:-30 03 * * *}
      RC_URL: ${RC_URL:-}
      RC_DATA: ${RC_DATA:-}
      IC_CREDENTIALS: ${IC_CREDENTIALS:-}
      IC_URL: ${IC_URL:-}
      IC_DATA: ${IC_DATA:-}
      MYSQL_HOST: db
    restart: unless-stopped
    volumes:
      - dumps:/var/backups/mysql:rw
    networks:
      - database-network
volumes:
  dumps:
     driver: local
     driver_opts:
        type: none
        o: bind
        device: ${PWD}/${DUMP_PATH:-backups}

networks:
    database-network:
      name: $MYSQL_DOCKER_NETWORK
      external: true
