FROM debian:bullseye-slim

ENV TZ="Europe/Prague"

RUN apt-get update && apt-get full-upgrade -y && apt-get install -y curl logrotate cron dumb-init bzip2 tzdata

RUN curl -LsS -O https://downloads.mariadb.com/MariaDB/mariadb_repo_setup && \
    chmod +x mariadb_repo_setup && \
    bash mariadb_repo_setup --mariadb-server-version=10.9 && \
    apt-get update && apt-get install -y mariadb-client && \
    mkdir -p /var/backups/mysql

COPY ./entrypoint.sh /
COPY ./mysql-backup.sh /etc/imt-sql-backup/
COPY ./rotate-mysql /etc/imt-sql-backup/

RUN chmod +x ./entrypoint.sh && chmod +x /etc/imt-sql-backup/mysql-backup.sh

ENTRYPOINT ["/usr/bin/dumb-init", "--", "/entrypoint.sh"]
